file = open('myDiary.txt','r')
print(file.read())
file = open('myDiary.txt','w')
file.write('I am 13 yrs old')
file = open('myDiary.txt','r')
print(file.read())
file = open('myDiary.txt','a')
file.write('\nI also do coding as well')
file = open('myDiary.txt','r')
print(file.read())