CREATE TABLE IF NOT EXISTS EMPLOYEE_FRAUD_LOG (
EMPLOYEE_NAME TEXT,
EMPLOYEE_ID TEXT PRIMARY KEY,
DEPARTMENT TEXT,
SUSPECTED_NOT TEXT
);

INSERT INTO EMPLOYEE_FRAUD_LOG (EMPLOYEE_NAME, EMPLOYEE_ID, DEPARTMENT, SUSPECTED_NOT)
VALUES
("TARUN KUMAR", "DXC-1001", "IT SECURITY", "NO"),
("JOHN SMITH", "DXC-2045", "FINANCE", "YES"),
("SARAH COOPER", "DXC-1182", "HUMAN RESOURCES", "NO"),
("AMIT PATEL", "DXC-3091", "PROCUREMENT", "YES"),
("ELENA ROSTOVA", "DXC-2554", "FINANCE", "YES");

SELECT *
FROM EMPLOYEE_FRAUD_LOG
WHERE SUSPECTED_NOT = "YES";