CREATE TABLE IF NOT EXISTS CUSTOMERS (
NAME TEXT,
CITY TEXT,
GRADE INTEGER
);

INSERT INTO CUSTOMERS (NAME, CITY, GRADE) VALUES
("ALICE SMITH", "NEW YORK", 120),
("BOB JONES", "LOS ANGELES", 85),
("CHARLIE BROWN", "CHICAGO", 105),
("DIANA PRINCE", "NEW YORK", 90),
("EVAN WRIGHT", "HOUSTON", 115);

SELECT * FROM CUSTOMERS
WHERE CITY = "NEW YORK" OR GRADE > 100;

SELECT * FROM CUSTOMERS
WHERE CITY = "NEW YORK" AND GRADE > 100;