CREATE TABLE IF NOT EXISTS NEWS (
HEADLINE TEXT,
DAY TEXT,
DATE TEXT
);

INSERT INTO NEWS (HEADLINE, DAY, DATE) VALUES 
("GLOBAL TECH SUMMIT KICKS OFF IN SAN FRANCISCO", "SUNDAY", "2026-06-14"),
("MAJOR BANK CRYPTO WALLETS HACKED BY ANONYMOUS GROUP", "SUNDAY", "2026-06-14"),
("NEW AI MODELS REVOLUTIONIZE DATA ANALYSIS SPEED", "MONDAY", "2026-06-15"),
("STOCKS REACH RECORD HIGHS AMID ECONOMIC GROWTH", "TUESDAY", "2026-06-16"),
("HACKERS BREACH INTEL AGENCY DATABASES IN SEATTLE", "MONDAY", "2026-06-15"),
("RENEWABLE ENERGY PROJECTS RECEIVE MAJOR FUNDING", "WEDNESDAY", "2026-06-17"),
("SPACE AGENCY ANNOUNCES MARS ROVER LAUNCH DATE", "THURSDAY", "2026-06-18"),
("TECH FIRMS RUSH PATCHES AFTER HACKING TOOL LEAKED", "TUESDAY", "2026-06-16"),
("DEEP SEA EXPLORATION TEAMS DISCOVER NEW SPECIES", "FRIDAY", "2026-06-19"),
("BREAKTHROUGH MEDICAL TRIALS SHOW 90 PERCENT SUCCESS", "SATURDAY", "2026-06-20");

SELECT HEADLINE AS "BEST HACKING NEWS", 
       DATE AS RECENT
FROM NEWS
WHERE HEADLINE LIKE "%HACK%"
ORDER BY DATE DESC;