CREATE TABLE IF NOT EXISTS EMPLOYEES (
NAME TEXT,
DEPARTMENT TEXT,
SALARY INTEGER
);

INSERT INTO EMPLOYEES (NAME, DEPARTMENT, SALARY) VALUES 
("JOHN DOE", "ENGINEERING", 85000),
("JANE SMITH", "MARKETING", 65000),
("SAM WILSON", "FINANCE", 75000),
("ALICE BROWN", "HUMAN RESOURCES", 60000),
("BOB JOHNSON", "SALES", 55000),
("CHARLIE GREEN", "LEGAL", 95000),
("DIANA PRINCE", "OPERATIONS", 70000);

SELECT SUM (SALARY) AS "TOTAL SALARY" FROM EMPLOYEES;

SELECT COUNT (DEPARTMENT) AS "NUMBER OF DEPARTMENTS" FROM EMPLOYEES;

SELECT MIN (SALARY) AS "MIN_SALARY",
       MAX (SALARY) AS "MAX_SALARY"
FROM EMPLOYEES;